name: Build

on:
  push:
    branches:
      - master
      - actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16'
      - run: flutter pub get
      # - run: flutter test no test de momento
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v4
        with:
          name: AuthenticatorPro
          path: build/build/app/outputs/apk/release/*.apk